### ISSUE TITLE
训练好的模型有下载链接吗

### ISSUE THREAD

**Issue by yancccc** [Zhengbo-Zhang/FADE#4]
FileNotFoundError: [Errno 2] No such file or directory: '\\mnt\\data1\\ghh\\yolov5\\runs\\train\\exp29\\last.pt'

**Comment by Zhengbo-Zhang** [comment]
Hi, sorry for the late reply. We have updated the download link for the pre-trained weight in the readme. Please check it, thanks.

> our pre-trained weight can be downloaded from [Google Drive](https://drive.google.com/file/d/1pI8PJ9BSwOinF7tEqqj3JZeNDOnC2--9/view?usp=sharing) or [Baidu Yun](https://pan.baidu.com/s/1MklhfAT4oigkrrB78AARGw?pwd=shyw)
